version: "3"

services:
  mysql-db:
    image: mysql:8.0.28
    restart: always
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - employee-system-db:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  backend:
    build: ./employee-system-api
    restart: always
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL= jdbc:mysql://mysql-db:3306/employee_system?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=admin
    depends_on:
      - mysql-db

  frontend:
    build: ./employee-system-ui
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - backend

volumes:
  employee-system-db:
