version: "3"

services:
  backend:
    build: ./employee-system-api
    restart: always
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL= jdbc:mysql://mysql-db:3306/employee_system?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=admin
    depends_on:
      - mysql-db
