version: "3"

services:
  mysql-db:
    image: mysql:8.0.28
    restart: always
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - employee-system-db:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

volumes:
  employee-system-db:
